platform :ios, '11.1'
use_frameworks!

def rx
  pod 'RealmSwift'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxRealm'
  pod 'RxDataSources'
  pod 'RxOptional'
end

def misc
  pod 'Kanna', '~> 4.0.0'
  pod 'Reusable'
  pod 'StringExtensionHTML'
  pod 'SwiftyStoreKit'
  pod 'IceCream'
  pod 'Zephyr'
end

def ui
  pod 'FloatingPanel'
  pod 'Highlightr', :git => 'https://github.com/itsmeichigo/Highlightr.git'
  pod 'SnapKit'
  pod 'PanModal'
  pod 'Tags'
  pod 'SVProgressHUD'
end

def testing
  pod 'Quick'
  pod 'Nimble'
end

target 'AlgoApp' do
  ui
  rx
  misc
end

target 'AlgoAppTests' do
  rx
  misc
  testing
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  end
 end
end
