source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.1'
use_frameworks!
inhibit_all_warnings!

def rx
  pod 'RealmSwift'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxRealm'
  pod 'RxDataSources'
  pod 'RxOptional'
end

def misc
  pod 'Kanna', '~> 4.0.0'
  pod 'Reusable'
  pod 'StringExtensionHTML'
  pod 'SwiftyStoreKit'
  pod 'IceCream'
  pod 'Zephyr'
end

def ui
  pod 'FloatingPanel'
  pod 'Highlightr', :git => 'https://github.com/itsmeichigo/Highlightr.git'
  pod 'SnapKit'
  pod 'PanModal'
  pod 'Tags'
  pod 'SVProgressHUD'
end

def testing
  pod 'Quick'
  pod 'Nimble'
end

target 'AlgoApp' do
  ui
  rx
  misc
end

target 'AlgoAppTests' do
  rx
  misc
  testing
end
